### ISSUE TITLE
Lightning talks

### ISSUE THREAD

**Issue by gnugat** [SymfonyCon/2015-talks#3]
Where should we put the lightning talks? I've got the slides for [PHP-FIG, the PSRs you don't know about](https://speakerdeck.com/michaelcullum/php-fig-the-psrs-you-dont-know-about)

**Comment by mykiwi** [comment]
At the bottom like for [SymfonyCon/2014-talks](https://github.com/SymfonyCon/2014-talks), but I don't have the list (and did not see them).
How do you know that these slides were in lightning talks?

**Comment by gnugat** [comment]
Because of this tweet: https://twitter.com/michaelcullumuk/status/672778522931408896
